### ISSUE TITLE
Create 'ESB event priority' entity

### ISSUE THREAD

**Issue by vritant** [lightblue-platform/lightblue-esb-hook#11]
we need to decide what fields belong in the event priority entity.
- CREATED discussion on June 15th

current thinking :
-  _id type:uid
-  priority : integer
-  entity name : string
-  entity version : string
-  lightblue query : string

**Comment by vritant** [comment]
Note, this discussion can be closed only after we have an agreed upon solution for #3 , but we have a fairly good idea of what it will look like to start.
proposed fields list:
-  _id type:uid
-  description : string
-  value: integer
-  end system name: string
-  root entity name: string
-  created by: string
-  field name: string
-  root event key like: string
-  field event key like: string
-  operation like: string

**Comment by vritant** [comment]
some context for confused viewers, I posted current thinking from @jewzaam 's comments else where.

@jewzaam  I think a core difference in our approach is creating dynamic query based on configurations vs. configuring the query in the document.

fyi @paterczm

**Comment by jewzaam** [comment]
@vritant how about supporting both static query and dynamic?  Initial development would be only for static query.  In the future, enhance things to generate a query based on config if no static query is defined.  this will allow transition from static to dynamic query possible over time and eventually make configuring priority easier for support.  We need to get some minimal product done first so we can move forward with other things.  Having an easy to use interface would be great, but it's not a feature that blocks support of integration.  Just means more training up front initially or a fewer number of people can define the priority.

**Comment by vritant** [comment]
@jewzaam not sure about supporting both, but static now and dynamic later seems okay.

here is my latest suggestion:
- _id type:uid
- end system name : string
- lightblue query : string (example: update priority_value to be 5 when blah=blah and blah=blah and priority value is null )

**Comment by vritant** [comment]
@jewzaam  does this mean we are running native queries and not using the lightblue client in the mediator ??? wont this complicate things a bit ? 
Lightblue client is more convinient to use, but now we will need to get the lightblue camel endpoints working with either both native queries and lightblue client or just native everywhere.

**Comment by bserdar** [comment]
Lightblue client some serious rework. I have a ticket to allow lightblue
expressions as query parts, but there is a workaround, and you can use the
client with a native lightblue query.

**Comment by bserdar** [comment]
..Lightblue client _needs_ some serious rework...

**Comment by vritant** [comment]
@bserdar  are you recommending we do not use client in this project?

**Comment by vritant** [comment]
FYI @alowens

**Comment by bserdar** [comment]
Use the client, but fix its problems first before you're heavily invested
in it.

These are important, and will cause a lot of trouble unless fixed:

https://github.com/lightblue-platform/lightblue-client/issues/109
https://github.com/lightblue-platform/lightblue-client/issues/112

This, when fixed, will cause a lot of changes to clients:

https://github.com/lightblue-platform/lightblue-client/issues/122

**Comment by vritant** [comment]
@jewzaam ,
@paterczm and I discussed further, and we would like to re-visit this decision.
The configuration solution would not be a dynamic lightblue query constructed from configuration like I mentioned earlier in this discussion, but we will load the configuration and compute the priority value in java to make a simple update with the priority value for each unprocessed event.with this solution in mind, it does not make sense to write lightblue queries now and switch to a "most-specific-match" algorithm later.
please comment.

**Comment by jewzaam** [comment]
Do you have some example of this "most specific match" algo you keep
bringing up?  I think I understand what you're saying but I don't see how
it will be easily implemented.  You're dealing with a query language, be it
lightblue or SQL, and the results you get back specifically match the
criteria of the query.  There is no fuzzy logic to it anywhere.

**Comment by vritant** [comment]
@jewzaam  here is a simple way to implement specificity, by introducing a "weight" field 
proposed fields list:
-  _id type:uid
-  description : string
-  priorityValue: integer
-  priorityWeight: integer
-  endSystem: string
-  entity: string
-  rootEntity: string
-  created by: string
-  rootIdentityRegex: string
-  identityRegex: string
-  operation: string

Algorithm is for each event, to traverse the priority rules in the order of highest weight. the first matching rule wins.
specificity is defined at configuration time.

**Comment by jewzaam** [comment]
@vritant what's the difference between priority "weight" and "value"?  Seems like you're just replacing words given your statement has highest priority now picked by weight only: `Algorithm is for each event, to traverse the priority rules in the order of highest weight. the first matching rule wins.`

**Comment by vritant** [comment]
@jewzaam the weight is used to decide amongst rules when multiple rules could match the event.
the priority value is the priority assigned to the event based on which rule is chosen.

**Comment by jewzaam** [comment]
So:
- weight = rule priority
- value = event priority
  ?

**Comment by vritant** [comment]
@jewzaam sure, that works.. do you recommend I rename the field to rule priority?

**Comment by jewzaam** [comment]
Rename to something that's more self descriptive, yes.

**Comment by dcrissman** [comment]
I do not believe this belongs as a collection of the publish hook. I think this should be an application specific collection.

The application may choose to use some other form of configuration, but I do not believe the publish hook should dictate how this should be.

**Comment by jewzaam** [comment]
@dcrissman could you clarify what you think shouldn't be part of the hook?  I think the discussion around priority is the fields on the entity for event key.  The values wouldn't be set by the hook, it would be set by the mediator enricher component?

**Comment by dcrissman** [comment]
The publish hook has the 'event' collection, which has a priority field. That field will be initiated to the hook's configured defaultPriority if one was set.

I understand this issue to be for a separate collection that contains rules for how that priority field should be updated, if needed. But the purposed new collection has nothing to do with the publish hook as a separate application (aka mediator) is responsible for updating the event priority field if something other than the defaultPriority is desired. How that application makes the decision (in this example using the new collection) is of no concern to the hook.
