### ISSUE TITLE
Create 'ESB event config' entity

### ISSUE THREAD

**Issue by vritant** [lightblue-platform/lightblue-esb-hook#12]
we need to decide what fields belong in the event config entity.

```
CREATED discussion on June 15th
```

current thinking :
- _id type:uid
- config name : string
- config value : string

**Comment by dcrissman** [comment]
I do not believe this belongs as a collection of the publish hook. I think this should be an application specific collection.

The application may choose to use a properties file or some other form of configuration, but I do not believe the publish hook should dictate how this should be.
