### ISSUE TITLE
update configurations - set all publish hook configurations as a part of identityConfigurations

### ISSUE THREAD

**Issue by vritant** [lightblue-platform/lightblue-esb-hook#26]
for example, change from :
{
    "entityName": "Country",
    "rootEntityName": "Country",
    "endSystem": "COUNTRY",
    "defaultPriority": "100",
    "identityConfigurations":[{"integratedFieldsProjection":[{ "field":"name"},{ "field":"description"}],
                                           "identityProjection":[{ "field":"state"},{ "field":"code"}],
                                           "rootIdentityfields":["state","code"],
                                         }]
}

to: 
{
    "identityConfigurations":[{ 
    "entityName": "Country",
    "rootEntityName": "Country",
    "endSystem": "COUNTRY",
    "defaultPriority": "100",
    "integratedFieldsProjection":[{ "field":"name"},{ "field":"description"}],
    "identityProjection":[{ "field":"state"},{ "field":"code"}],
    "rootIdentityfields":["state","code"]
    }]
}

reason : configuration is more flexible.

**Comment by dcrissman** [comment]
I am going work on this as part of #22.

**Comment by dcrissman** [comment]
entityName is no longer part of the publish hook configurations as that will be auto set by the hook now.

Instead we now have esbRootEntityName & esbEventEntityName.
